### ISSUE TITLE
Please add a license

### ISSUE THREAD

**Issue by karan** [ximenpo/simple-cpp#1]
Without a license, this project isn't open source and no one can use the code.

Please use something like http://choosealicense.com/ to decide what license to use. I recommend MIT or GPL.

> A novel effort by [**Add a License Please**](https://github.com/karan/add-a-license-please)

**Comment by ximenpo** [comment]
Nice bot, thanks !

**Comment by ximenpo** [comment]
using MIT open source protocol.

**Comment by karan** [comment]
Thanks @ximenpo
